#
# .travis.yml - configuration file for the travis continuous integration service
#
# see https://docs.travis-ci.com/user/languages/php for more hints
#
language: php

php: [7.0]

before_install:
  # shutdown stuff on Travis, which may have a memory impact
  - sudo service --status-all
  - sudo free -m -t
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  - sudo free -m -t
  - sudo free -m -t | sudo grep "Total:" | sudo awk '{ if ($4 < 4000) print "\n\nCAUTION \n\nNOT ENOUGH MEMORY FOR THE DOWNLOADS ("$4" MB).\n\n" }'
  - ps aux --sort -rss | head -n15
  # install apt-fast to speedup later dependency installation
  - sudo add-apt-repository -y ppa:apt-fast/stable
  - sudo apt-get update -qq
  - sudo apt-get install -qq aria2 apt-fast 
  # add repos
  - sudo add-apt-repository -y ppa:ubuntu-wine/ppa
  # use apt-fast for installation of dependencies
  - sudo apt-fast -y update
  - sudo apt-fast -m -y install p7zip-full ca-certificates wine1.8

before_script:
  # start framebuffer (wine wants this)
  #- "export DISPLAY=:99.0"
  #- "sh -e /etc/init.d/xvfb start"
  #- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 640x480x16 -noreset"
  # adjust PHP env
  - phpenv config-add .travis.php.ini   # < increase memory
  - phpenv config-rm xdebug.ini # disable preinstalled PHP extension

script:
  #- sudo /opt/wine-staging/bin/wine --version
  #- wine --version #< ubuntu-wine/ppa
  #- wineconsole --version
  - aria2c --version
  - php /home/travis/build/WPN-XM/WPN-XM/bin/phing/phing-latest.phar main-part1 -verbose
  - php /home/travis/build/WPN-XM/WPN-XM/bin/phing/phing-latest.phar download-components
  #- php /home/travis/build/WPN-XM/WPN-XM/bin/phing/phing-latest.phar download-components-sequence
  #- cat downloads-cmds.txt
  #- sh downloads-cmds.txt
  - php /home/travis/build/WPN-XM/WPN-XM/bin/phing/phing-latest.phar main-part2
  # show content of folders
  - sudo ls -alh /home/travis/build/WPN-XM/WPN-XM/*
  - sudo ls -alh /home/travis/build/WPN-XM/WPN-XM/downloads/*

after_failure:
  - sudo free -m -t
  - sudo dmesg # < WTF is wrong with Travis?

# deploy the installer executables to github releases
deploy:
  provider: releases
  api_key:
    secure: EXN1Q+iXC9acOgUujeCxCQywzDCLQUWQbAa8GMxnqF1nBAvSDeXnTIBQnfDsuQZkWtSMz34zyC4ZN/eta9Lytq4yKMP4XvKVBP5bXQNanDzck+CuUFbnYKE8bVbON6mksN09H5/qt0QHWxjE/vlxCXdoD7Kaek3coWET9s82yXg=
  file_glob: true
  file: ${HOME}/build/${TRAVIS_REPO_SLUG}/_build/*.exe
  skip_cleanup: true
  on:
    tags: true #  the application is deployed, when a tag is applied to the commit

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#wpnxm"
    use_notice: true
    skip_join: true

git:
  depth: 10